version: "3.7"

services:
  traveller:
    image: postgres
    container_name: traveller
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=traveller
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=traveller
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
